/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unipampa.rp2.frames;

import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.unipampa.rp2.listaimoveis.Lista;
import org.unipampa.rp2.tiposimoveis.Apartamento;
import org.unipampa.rp2.tiposimoveis.Imovel;
import org.unipampa.rp2.tiposimoveis.Tipo;

/**
 *
 * @author vitao375
 */
public class FrameApartamento2 extends javax.swing.JFrame {

    private Lista listaApartamento;
    private boolean isEditar;
    private int isCod = 0;

    /**
     * Creates new form FrameApartamento2
     *
     * @param listaApartamento
     */
    public FrameApartamento2(Lista listaApartamento) {
        initComponents();
        this.setLocationRelativeTo(null);

        this.setTitle("Imobiliária - Apartamento");
        if (listaApartamento.lerArquivo()) {
        } else {
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado!");
        }

        this.listaApartamento = listaApartamento;
        
        try {
            Lista.startCodigo();
        } catch (IOException ex) {

        }

        jTabbedPaneCasa.setEnabledAt(1, false);
        jTabbedPaneCasa.setEnabledAt(0, true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneCasa = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListFrameCasa = new javax.swing.JList<>();
        jButtonVoltar = new javax.swing.JButton();
        jButtonOrdenar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonDetalhes = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jComboBoxPesquisa = new javax.swing.JComboBox<>();
        jTextFieldBusca = new javax.swing.JTextField();
        jButtonBuscarCasa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelNomeEdificio = new javax.swing.JLabel();
        jLabelNApartamento = new javax.swing.JLabel();
        jLabelNQ = new javax.swing.JLabel();
        jLabelAnoC = new javax.swing.JLabel();
        jLabelNVG = new javax.swing.JLabel();
        jLabelVCondominio = new javax.swing.JLabel();
        jLabelAndar = new javax.swing.JLabel();
        jLabelLogradouro = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelAreaTotal = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonVoltarConsultar = new javax.swing.JButton();
        jTextFieldAndar = new javax.swing.JTextField();
        jTextFieldLogradouro = new javax.swing.JTextField();
        jTextFieldNomeEdificio = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldAreaTotal = new javax.swing.JTextField();
        jTextFieldValorCondominio = new javax.swing.JTextField();
        jTextFieldAnoC = new javax.swing.JTextField();
        jTextFieldNVGaragem = new javax.swing.JTextField();
        jTextFieldNApartamento = new javax.swing.JTextField();
        jTextFieldNQuartos = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneCasa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jScrollPane2.setViewportView(jListFrameCasa);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonOrdenar.setText("Ordenar");
        jButtonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonDetalhes.setText("Detalhes");
        jButtonDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalhesActionPerformed(evt);
            }
        });

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jComboBoxPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Valor", "Bairro" }));
        jComboBoxPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPesquisaItemStateChanged(evt);
            }
        });

        jTextFieldBusca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBuscaFocusLost(evt);
            }
        });
        jTextFieldBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscaActionPerformed(evt);
            }
        });
        jTextFieldBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBuscaKeyTyped(evt);
            }
        });

        jButtonBuscarCasa.setText("Buscar");
        jButtonBuscarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 64, Short.MAX_VALUE)
                        .addComponent(jButtonBuscarCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarCasa)
                    .addComponent(jComboBoxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDetalhes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOrdenar)
                        .addGap(134, 134, 134)
                        .addComponent(jButtonVoltar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPaneCasa.addTab("Consultar", jPanel1);

        jLabelNomeEdificio.setText("Nome do Edificio:*");

        jLabelNApartamento.setText("Número do Apartamento:*");

        jLabelNQ.setText("Numero de Quartos:*");

        jLabelAnoC.setText("Ano de Construção:*");

        jLabelNVG.setText("Número de Vagas na Garagem:*");

        jLabelVCondominio.setText("Valor do Condominio:*");

        jLabelAndar.setText("Andar:*");

        jLabelLogradouro.setText("Logradouro:*");

        jLabelBairro.setText("Bairro:*");

        jLabelAreaTotal.setText("Area Total:*");

        jLabelDescricao.setText("Descricao:*");

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonVoltarConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonVoltarConsultar.setText("Voltar");
        jButtonVoltarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarConsultarActionPerformed(evt);
            }
        });

        jTextFieldAndar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAndarKeyTyped(evt);
            }
        });

        jTextFieldAreaTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAreaTotalFocusLost(evt);
            }
        });
        jTextFieldAreaTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAreaTotalKeyTyped(evt);
            }
        });

        jTextFieldValorCondominio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldValorCondominioFocusLost(evt);
            }
        });
        jTextFieldValorCondominio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorCondominioKeyTyped(evt);
            }
        });

        jTextFieldAnoC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAnoCKeyTyped(evt);
            }
        });

        jTextFieldNVGaragem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNVGaragemKeyTyped(evt);
            }
        });

        jTextFieldNApartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNApartamentoKeyTyped(evt);
            }
        });

        jTextFieldNQuartos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNQuartosKeyTyped(evt);
            }
        });

        jLabelCidade.setText("Cidade:*");

        jLabelNumero.setText("Número:*");

        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonVoltarConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNQ, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNQuartos)
                                    .addComponent(jTextFieldNumero)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelAnoC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldAnoC, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelNomeEdificio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNomeEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelAndar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldAndar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelNVG, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNVGaragem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAreaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLogradouro)
                                    .addComponent(jTextFieldDescricao)
                                    .addComponent(jTextFieldAreaTotal)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNApartamento)
                                    .addComponent(jLabelCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNApartamento)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelVCondominio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldValorCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAndar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAreaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAreaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAnoC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelVCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldValorCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldAnoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNVG, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNVGaragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNQ, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumero)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltarConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPaneCasa.addTab("Detalhes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        Inicial voltar = new Inicial();
        voltar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarActionPerformed
        String[] textMessages = {"Codigo", "Valor", "Area", "Cancelar"};
        int x = JOptionPane.showOptionDialog(null, "Esclha uma opção para ordenar:", "Ordenação",
                JOptionPane.WHEN_IN_FOCUSED_WINDOW, JOptionPane.QUESTION_MESSAGE,
                null, textMessages, null);
        DefaultListModel lista = new DefaultListModel();
        switch (x) {
            case 0:
                listaApartamento.ordenarCodigo();
                listarCod(-1);
                listaApartamento.escreverArquivo();
                break;
            case 1:
                listaApartamento.ordenarValor();
                listarCod(-1);
                listaApartamento.escreverArquivo();
                break;
            case 2:
                listaApartamento.ordenarArea();
                listarCod(-1);
                listaApartamento.escreverArquivo();
                break;
        }
    }//GEN-LAST:event_jButtonOrdenarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        String cod = JOptionPane.showInputDialog("Informe o código da casa a ser removida.");
        int codigo;
        boolean error = false;
        if (cod == null || cod.equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o código novamente!");

        } else {
            for (int i = 0; i < cod.length(); i++) {
                if (!(Character.isDigit(cod.charAt(i)))) {
                    error = true;
                    break;
                }
            }
            if (error) {
                JOptionPane.showMessageDialog(null, "Informe apenas números!");
            } else {
                codigo = Integer.parseInt(cod);
                if (listaApartamento.excluir(codigo)) {
                    JOptionPane.showMessageDialog(this, "Apartamento removida com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Apartamento com o código: " + codigo + " não encontrada.");
                }
                if (listaApartamento.escreverArquivo()) {
                    JOptionPane.showMessageDialog(this, "Salvo");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar");
                }
            }

        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        String cod = JOptionPane.showInputDialog("Insira o código da Apartamento que deseja editar: ");
        boolean error = false;
        if (cod == null) {

        } else if (cod.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "ERRO 01 - Insira um valor");
        } else {
            for (int i = 0; i < cod.length(); i++) {
                if (!(Character.isDigit(cod.charAt(i)))) {
                    error = true;
                    break;
                }
            }

            if (error) {
                JOptionPane.showMessageDialog(null, "Insira apenas Números!");
            } else if (preencherCampos(Integer.parseInt(cod))) {
                jTabbedPaneCasa.setSelectedIndex(1);
                jTabbedPaneCasa.setEnabledAt(0, false);
                jTabbedPaneCasa.setEnabledAt(1, true);
                isEditar = true;
                isCod = Integer.parseInt(cod);
                ativarCampos();
            }
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalhesActionPerformed
        // TODO add your handling code here:
        String aux = "";
        boolean error = false;
        aux = JOptionPane.showInputDialog("Insira o código do objeto que deseja buscar: ");

        if (aux == null) {
        } else if (aux.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "ERRO 01 - Insira um valor");
        } else {
            for (int i = 0; i < aux.length(); i++) {
                if (!(Character.isDigit(aux.charAt(i)))) {
                    error = true;
                    break;
                }
            }

            if (error) {
                JOptionPane.showMessageDialog(null, "ERRO 02 - Insira somente número inteiros");
            } else if (preencherCampos(Integer.parseInt(aux))) {
                desativarCampos();
                jTabbedPaneCasa.setSelectedIndex(1);
                jTabbedPaneCasa.setEnabledAt(1, true);
                jTabbedPaneCasa.setEnabledAt(0, false);
            }
        }
    }//GEN-LAST:event_jButtonDetalhesActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        ativarCampos();
        limparCampos();
        jTabbedPaneCasa.setEnabledAt(0, false);
        jTabbedPaneCasa.setEnabledAt(1, true);
        jTabbedPaneCasa.setSelectedIndex(1);
        isEditar = false;
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jComboBoxPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPesquisaItemStateChanged
        jTextFieldBusca.setText("");
    }//GEN-LAST:event_jComboBoxPesquisaItemStateChanged

    private void jTextFieldBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscaActionPerformed

    private void jTextFieldBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscaKeyTyped
        if (jComboBoxPesquisa.getSelectedItem().toString().equals("Codigo")) {
            soNumeros(evt);
        } else if (jComboBoxPesquisa.getSelectedItem().toString().equals("Valor")) {
            soDouble(evt, jTextFieldBusca.getText());
        }
    }//GEN-LAST:event_jTextFieldBuscaKeyTyped

    private void jButtonBuscarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCasaActionPerformed
        // TODO add your handling code here:
        if (jTextFieldBusca.getText().trim().equals("")) {
            listarCod(-1);
        } else {
            switch (jComboBoxPesquisa.getSelectedItem().toString()) {
                case "Codigo":
                    listarCod(Integer.parseInt(jTextFieldBusca.getText().trim()));
                    break;
                case "Valor":
                    listarValor(Double.parseDouble(jTextFieldBusca.getText().trim()));
                    break;
                case "Bairro":
                    listarBairro(jTextFieldBusca.getText().trim());
                    break;

            }
        }
    }//GEN-LAST:event_jButtonBuscarCasaActionPerformed

    private void jButtonVoltarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarConsultarActionPerformed
        jTabbedPaneCasa.setEnabledAt(1, false);
        jTabbedPaneCasa.setEnabledAt(0, true);
        jTabbedPaneCasa.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonVoltarConsultarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (jTextFieldAndar.getText().equals("")
                || jTextFieldAnoC.getText().equals("")
                || jTextFieldAreaTotal.getText().equals("")
                || jTextFieldBairro.getText().equals("")
                || jTextFieldDescricao.getText().equals("")
                || jTextFieldLogradouro.getText().equals("")
                || jTextFieldNApartamento.getText().equals("")
                || jTextFieldNQuartos.getText().equals("")
                || jTextFieldNVGaragem.getText().equals("")
                || jTextFieldNomeEdificio.getText().equals("")
                || jTextFieldValorCondominio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");

        } else if (isEditar) {
            Apartamento p = new Apartamento(jTextFieldCidade.getText(), jTextFieldBairro.getText(),
                    jTextFieldLogradouro.getText(), Integer.parseInt(jTextFieldNumero.getText()),
                    Double.parseDouble(jTextFieldValorCondominio.getText()), jTextFieldNomeEdificio.getText(),
                    Integer.parseInt(jTextFieldAndar.getText()), Integer.parseInt(jTextFieldNApartamento.getText()),
                    Integer.parseInt(jTextFieldAnoC.getText()), Integer.parseInt(jTextFieldNQuartos.getText()),
                    Integer.parseInt(jTextFieldNVGaragem.getText()), Double.parseDouble(jTextFieldValorCondominio.getText()),
                    jTextFieldDescricao.getText(), Double.parseDouble(jTextFieldAreaTotal.getText()));

            if (listaApartamento.editar(isCod, p)) {
                jTabbedPaneCasa.setEnabledAt(1, false);
                jTabbedPaneCasa.setEnabledAt(0, true);
                jTabbedPaneCasa.setSelectedIndex(0);
                try {
                    listaApartamento.gravarUltimoCod(isCod);
                } catch (IOException ex) {
                    Logger.getLogger(FrameApartamento2.class.getName()).log(Level.SEVERE, null, ex);
                }
                listaApartamento.escreverArquivo();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao Editar");
            }
        } else {
            Apartamento p = new Apartamento(jTextFieldCidade.getText(), jTextFieldBairro.getText(),
                    jTextFieldLogradouro.getText(), Integer.parseInt(jTextFieldNumero.getText()),
                    Double.parseDouble(jTextFieldValorCondominio.getText()), jTextFieldNomeEdificio.getText(),
                    Integer.parseInt(jTextFieldAndar.getText()), Integer.parseInt(jTextFieldNApartamento.getText()),
                    Integer.parseInt(jTextFieldAnoC.getText()), Integer.parseInt(jTextFieldNQuartos.getText()),
                    Integer.parseInt(jTextFieldNVGaragem.getText()), Double.parseDouble(jTextFieldValorCondominio.getText()),
                    jTextFieldDescricao.getText(), Double.parseDouble(jTextFieldAreaTotal.getText()));

            if (listaApartamento.incluir(p)) {
                jTabbedPaneCasa.setEnabledAt(1, false);
                jTabbedPaneCasa.setEnabledAt(0, true);
                jTabbedPaneCasa.setSelectedIndex(0);
                try {
                    this.listaApartamento.gravarUltimoCod(p.getCod());
                } catch (IOException ex) {
                    Logger.getLogger(FrameApartamento2.class.getName()).log(Level.SEVERE, null, ex);
                }
                listaApartamento.escreverArquivo();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao Incluir");
            }

        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldBuscaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBuscaFocusLost
        if(jTextFieldBusca.getText().trim().equals(".")){
            jTextFieldBusca.setText("");
        }
        
    }//GEN-LAST:event_jTextFieldBuscaFocusLost

    private void jTextFieldAndarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAndarKeyTyped
        soNumeros(evt);
    }//GEN-LAST:event_jTextFieldAndarKeyTyped

    private void jTextFieldAreaTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAreaTotalKeyTyped
        soDouble(evt, jTextFieldAreaTotal.getText());
    }//GEN-LAST:event_jTextFieldAreaTotalKeyTyped

    private void jTextFieldAnoCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnoCKeyTyped
        soNumeros(evt);
    }//GEN-LAST:event_jTextFieldAnoCKeyTyped

    private void jTextFieldValorCondominioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorCondominioKeyTyped
        soDouble(evt, jTextFieldValorCondominio.getText());
    }//GEN-LAST:event_jTextFieldValorCondominioKeyTyped

    private void jTextFieldNVGaragemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNVGaragemKeyTyped
        soNumeros(evt);
    }//GEN-LAST:event_jTextFieldNVGaragemKeyTyped

    private void jTextFieldNApartamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNApartamentoKeyTyped
        soNumeros(evt);
    }//GEN-LAST:event_jTextFieldNApartamentoKeyTyped

    private void jTextFieldNQuartosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNQuartosKeyTyped
        soNumeros(evt);
    }//GEN-LAST:event_jTextFieldNQuartosKeyTyped

    private void jTextFieldNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyTyped
        soNumeros(evt);
    }//GEN-LAST:event_jTextFieldNumeroKeyTyped

    private void jTextFieldAreaTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAreaTotalFocusLost
        if(jTextFieldAreaTotal.getText().trim().equals(".")){
            jTextFieldAreaTotal.setText("");
        }
    }//GEN-LAST:event_jTextFieldAreaTotalFocusLost

    private void jTextFieldValorCondominioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorCondominioFocusLost
        if(jTextFieldValorCondominio.getText().trim().equals(".")){
            jTextFieldValorCondominio.setText("");
        }
    }//GEN-LAST:event_jTextFieldValorCondominioFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApartamento2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApartamento2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApartamento2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApartamento2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApartamento2(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarCasa;
    private javax.swing.JButton jButtonDetalhes;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonOrdenar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JButton jButtonVoltarConsultar;
    private javax.swing.JComboBox<String> jComboBoxPesquisa;
    private javax.swing.JLabel jLabelAndar;
    private javax.swing.JLabel jLabelAnoC;
    private javax.swing.JLabel jLabelAreaTotal;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelNApartamento;
    private javax.swing.JLabel jLabelNQ;
    private javax.swing.JLabel jLabelNVG;
    private javax.swing.JLabel jLabelNomeEdificio;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelVCondominio;
    private javax.swing.JList<String> jListFrameCasa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPaneCasa;
    private javax.swing.JTextField jTextFieldAndar;
    private javax.swing.JTextField jTextFieldAnoC;
    private javax.swing.JTextField jTextFieldAreaTotal;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldBusca;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNApartamento;
    private javax.swing.JTextField jTextFieldNQuartos;
    private javax.swing.JTextField jTextFieldNVGaragem;
    private javax.swing.JTextField jTextFieldNomeEdificio;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldValorCondominio;
    // End of variables declaration//GEN-END:variables

    /**
     * Recebe o codigo e adiciona a lista a monografia selecionada
     *
     * @param cod
     */
    public void listarCod(int cod) {
        DefaultListModel listModel = new DefaultListModel();
        if (cod == -1) {
            List<Imovel> list = listaApartamento.getLista();
            for (Imovel casa : list) {
                listModel.addElement(casa.toString());
            }
            jListFrameCasa.setModel(listModel);
        } else {
            Imovel casa = listaApartamento.consultar(cod);
            if (casa == null) {
                JOptionPane.showMessageDialog(null, "Não encontrado");
            } else {
                listModel.addElement(casa.toString());
            }

            jListFrameCasa.setModel(listModel);//Mudar a lista
        }
    }

    public void listarValor(double valor) {
        DefaultListModel listModel = new DefaultListModel();
        List<Imovel> casa = listaApartamento.pesquisaValor(valor);

        if (casa == null) {
            JOptionPane.showMessageDialog(null, "Não encontrado");

        } else {
            for (Imovel home : casa) {
                listModel.addElement(home.toString());
            }
        }

        jListFrameCasa.setModel(listModel);
    }

    public void listarBairro(String bairro) {
        DefaultListModel listModel = new DefaultListModel();
        List<Imovel> apartamnto = listaApartamento.pesquisaBairro(bairro);

        if (apartamnto == null) {
            JOptionPane.showMessageDialog(null, "Não encontrado");
        } else {
            for (Imovel home : apartamnto) {
                listModel.addElement(home.toString());
            }
        }

        jListFrameCasa.setModel(listModel);
    }

    public void soNumeros(java.awt.event.KeyEvent evt) {
        char aux = evt.getKeyChar();
        if (!Character.isDigit(aux)) {
            evt.consume();
        }
    }

    public void soDouble(java.awt.event.KeyEvent evt, String text) {
        char aux = evt.getKeyChar();
        int tem = 0;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '.') {
                tem++;
                break;
            }
        }

        if (aux == '.') {
            if (tem != 0) {
                evt.consume();
            }
        } else if (!Character.isDigit(aux)) {
            evt.consume();
        }
    }

    /**
     * Retorna true caso consiga preencher os campos com o objeto do codigo
     * selecionado e false caso contrário
     *
     * @param cod
     * @return
     */
    public boolean preencherCampos(int cod) {

        Apartamento a = (Apartamento) listaApartamento.consultar(cod);
        if (a != null) {
            jTextFieldAndar.setText(String.valueOf(a.getAndar()));
            jTextFieldAnoC.setText(String.valueOf(a.getAnoConstrucao()));
            jTextFieldAreaTotal.setText(String.valueOf(a.getAreaTotal()));
            jTextFieldBairro.setText(a.getBairro());
            jTextFieldDescricao.setText(a.getDescricao());
            jTextFieldLogradouro.setText(a.getLogradouro());
            jTextFieldNApartamento.setText(String.valueOf(a.getNroApartamento()));
            jTextFieldNQuartos.setText(String.valueOf(a.getNroQuartos()));
            jTextFieldNVGaragem.setText(String.valueOf(a.getVgsGaragem()));
            jTextFieldNomeEdificio.setText(a.getNomeEdificio());
            jTextFieldValorCondominio.setText(String.valueOf(a.getValorCondominio()));
            jTextFieldCidade.setText(a.getCidade());
            jTextFieldNumero.setText(String.valueOf(a.getNumero()));
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "ERRO 03 - Imóvel não encontrado");
            return false;
        }
    }

    private void limparCampos() {
        jTextFieldAndar.setText("");
        jTextFieldAnoC.setText("");
        jTextFieldAreaTotal.setText("");
        jTextFieldBairro.setText("");
        jTextFieldDescricao.setText("");
        jTextFieldLogradouro.setText("");
        jTextFieldNApartamento.setText("");
        jTextFieldNQuartos.setText("");
        jTextFieldNVGaragem.setText("");
        jTextFieldNomeEdificio.setText("");
        jTextFieldValorCondominio.setText("");
        jTextFieldCidade.setText("");
        jTextFieldNumero.setText("");
    }

    private void ativarCampos() {
        jTextFieldAndar.setEnabled(true);
        jTextFieldAnoC.setEnabled(true);
        jTextFieldAreaTotal.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldDescricao.setEnabled(true);
        jTextFieldLogradouro.setEnabled(true);
        jTextFieldNApartamento.setEnabled(true);
        jTextFieldNQuartos.setEnabled(true);
        jTextFieldNVGaragem.setEnabled(true);
        jTextFieldNomeEdificio.setEnabled(true);
        jTextFieldValorCondominio.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
    }

    private void desativarCampos() {
        jTextFieldAndar.setEnabled(false);
        jTextFieldAnoC.setEnabled(false);
        jTextFieldAreaTotal.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldDescricao.setEnabled(false);
        jTextFieldLogradouro.setEnabled(false);
        jTextFieldNApartamento.setEnabled(false);
        jTextFieldNQuartos.setEnabled(false);
        jTextFieldNVGaragem.setEnabled(false);
        jTextFieldNomeEdificio.setEnabled(false);
        jTextFieldValorCondominio.setEnabled(false);
        jTextFieldCidade.setEnabled(false);
        jTextFieldNumero.setEnabled(false);
    }
}
