/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unipampa.rp2.frames;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.unipampa.rp2.tiposimoveis.Terreno;
import org.unipampa.rp2.listaimoveis.Lista;
import org.unipampa.rp2.tiposimoveis.Imovel;

/**
 *
 * @author Vanderlan Mengotti
 */
public class FrameTerreno extends javax.swing.JFrame {

    Lista listaTerreno;
    private boolean isEdit = false;
    private int codEdit = 0;

    /**
     * Creates new form FrameTerreno
     */
    public FrameTerreno(Lista listaTerreno) {
        initComponents();

        this.listaTerreno = listaTerreno;
        this.setLocationRelativeTo(null);
        this.setTitle("Imobiliária - Terreno");

        if (listaTerreno.lerArquivo()) {

        } else {
            JOptionPane.showMessageDialog(null, "Arquivo Não Encontrado");
        }
        jButtonDetalhe.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);


        jTabbedPaneGuias.setEnabledAt(1, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneGuias = new javax.swing.JTabbedPane();
        jPanelCadastrar = new javax.swing.JPanel();
        jButtonIncluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonBuscarC = new javax.swing.JButton();
        jTextFieldCodBusc = new javax.swing.JTextField();
        jScrollPaneLista = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButtonVoltar = new javax.swing.JButton();
        jButtonDetalhe = new javax.swing.JButton();
        jComboBoxBusc = new javax.swing.JComboBox();
        jButtonOrdenar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelLog = new javax.swing.JLabel();
        jTextFieldLog = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabelDesc = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabelAreaTotal = new javax.swing.JLabel();
        jTextFieldAtotal = new javax.swing.JTextField();
        jLabelDimençaoF = new javax.swing.JLabel();
        jTextFieldDimencaoF = new javax.swing.JTextField();
        jLabelDimencaoL = new javax.swing.JLabel();
        jTextFieldDimencaoL = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonVoltando = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonBuscarC.setText("Buscar");
        jButtonBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCActionPerformed(evt);
            }
        });

        jTextFieldCodBusc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCodBuscFocusLost(evt);
            }
        });
        jTextFieldCodBusc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodBuscKeyTyped(evt);
            }
        });

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPaneLista.setViewportView(jList1);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonDetalhe.setText("Detalhes");
        jButtonDetalhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalheActionPerformed(evt);
            }
        });

        jComboBoxBusc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Valor", "Bairro" }));
        jComboBoxBusc.setAutoscrolls(true);
        jComboBoxBusc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxBuscItemStateChanged(evt);
            }
        });

        jButtonOrdenar.setText("Ordenar");
        jButtonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastrarLayout = new javax.swing.GroupLayout(jPanelCadastrar);
        jPanelCadastrar.setLayout(jPanelCadastrarLayout);
        jPanelCadastrarLayout.setHorizontalGroup(
            jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxBusc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDetalhe, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                        .addComponent(jTextFieldCodBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscarC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOrdenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneLista))
                .addContainerGap())
        );
        jPanelCadastrarLayout.setVerticalGroup(
            jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscarC)
                    .addComponent(jComboBoxBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOrdenar)
                    .addComponent(jButtonIncluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDetalhe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar))
                    .addComponent(jScrollPaneLista, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPaneGuias.addTab("Consultar", jPanelCadastrar);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));

        jLabelNumero.setText("Número:*");

        jTextFieldNumero.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyTyped(evt);
            }
        });

        jLabelLog.setText("Logradouro:*");

        jTextFieldLog.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabelBairro.setText("Bairro:*");

        jTextFieldBairro.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabelCidade.setText("Cidade:*");

        jTextFieldCidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabelValor.setText("Valor:*");

        jTextFieldValor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldValorKeyTyped(evt);
            }
        });

        jLabelDesc.setText("Descrição:*");

        jTextFieldDescricao.setToolTipText("");
        jTextFieldDescricao.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabelAreaTotal.setText("Área Total:*");

        jTextFieldAtotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAtotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAtotalKeyTyped(evt);
            }
        });

        jLabelDimençaoF.setText("Dimenção Frente (m):*");

        jTextFieldDimencaoF.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDimencaoF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDimencaoFKeyTyped(evt);
            }
        });

        jLabelDimencaoL.setText("Dimenção Lado (m):*");

        jTextFieldDimencaoL.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDimencaoL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDimencaoLKeyTyped(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonVoltando.setText("Voltar");
        jButtonVoltando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltandoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonVoltando)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAreaTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAtotal))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDimençaoF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldDimencaoF, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBairro))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldValor)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDimencaoL)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDimencaoL, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCidade)
                                    .addComponent(jLabelLog))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldLog, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCidade)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDesc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumero)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLog)
                    .addComponent(jTextFieldLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairro)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValor)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDesc)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDimencaoL)
                        .addComponent(jTextFieldDimencaoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAreaTotal)
                        .addComponent(jTextFieldAtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDimençaoF)
                    .addComponent(jTextFieldDimencaoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltando)
                    .addComponent(jButtonSalvar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPaneGuias.addTab("Dados", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneGuias)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneGuias)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        jTabbedPaneGuias.setSelectedIndex(1);
        jTabbedPaneGuias.setEnabledAt(1, true);
        jTabbedPaneGuias.setEnabledAt(0, false);
        ativarCampos();
        limparCampos();
        isEdit = false;
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        jButtonSalvar.setEnabled(true);
        isEdit = true;
        mudarAbas(0, 1);
        int cod = getCod(jList1.getSelectedValue().toString());
        //Pega o codigo selecionado. Na lista.
        this.codEdit = cod; //Variavel de classe para saber o código a ser editado.
        preencherCampos(cod);
        ativarCampos();

    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCActionPerformed
        // TODO add your handling code here:
        String indice = jComboBoxBusc.getSelectedItem().toString();
        if (jTextFieldCodBusc.getText().trim().equals("")) {
            listar();
        } else {

            switch (indice) {
                case "Codigo":
                    listarCodigo(Integer.parseInt(jTextFieldCodBusc.getText().trim()));
                    break;
                case "Valor":
                    listarValor(Double.parseDouble(jTextFieldCodBusc.getText().trim()));
                    break;
                case "Bairro":
                    listarBairro(jTextFieldCodBusc.getText().trim());
                    break;
            }
        }
    }//GEN-LAST:event_jButtonBuscarCActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        Inicial voltar = new Inicial();
        voltar.setVisible(true);// Deixar Visível
        this.dispose();// fechar
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonVoltandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltandoActionPerformed
        // TODO add your handling code here:
        jTabbedPaneGuias.setSelectedIndex(0);
        jTabbedPaneGuias.setEnabledAt(0, true);//index abas. 
        jTabbedPaneGuias.setEnabledAt(1, false);
    }//GEN-LAST:event_jButtonVoltandoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        if (jTextFieldAtotal.getText().trim().equals("") || jTextFieldBairro.getText().trim().equals("")
                || jTextFieldCidade.getText().trim().equals("") || jTextFieldDescricao.getText().trim().equals("")
                || jTextFieldDimencaoF.getText().trim().equals("") || jTextFieldDimencaoL.getText().trim().equals("")
                || jTextFieldLog.getText().trim().equals("") || jTextFieldNumero.getText().trim().equals("")
                || jTextFieldValor.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "É necessário o preenchimento de todos os campos");
        } else if (!isEdit) {

            Terreno t = new Terreno(Integer.parseInt(jTextFieldNumero.getText()),
                    Double.parseDouble(jTextFieldValor.getText()), jTextFieldCidade.getText(),
                    jTextFieldDescricao.getText(), jTextFieldLog.getText(), Double.parseDouble(jTextFieldAtotal.getText()),
                    jTextFieldBairro.getText(), Double.parseDouble(jTextFieldDimencaoF.getText()), Double.parseDouble(jTextFieldDimencaoL.getText()));

            listaTerreno.incluir(t);
            limparCampos();
            listar();
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");

            if (listaTerreno.escreverArquivo()) {
                JOptionPane.showMessageDialog(null, "ESCRITO COM SUCESSO");
            } else {
                JOptionPane.showMessageDialog(null, "Erro Ao Salvar");
            }
        } else {
            Terreno t = new Terreno(Integer.parseInt(jTextFieldNumero.getText()),
                    Double.parseDouble(jTextFieldValor.getText()), jTextFieldCidade.getText(),
                    jTextFieldDescricao.getText(), jTextFieldLog.getText(), Double.parseDouble(jTextFieldAtotal.getText()),
                    jTextFieldBairro.getText(), Double.parseDouble(jTextFieldDimencaoF.getText()), Double.parseDouble(jTextFieldDimencaoL.getText()));

            if (listaTerreno.editar(codEdit, t)) {
                JOptionPane.showMessageDialog(null, "Editado com sucesso");
                if (listaTerreno.escreverArquivo()) {
                    JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Não salvo ! ERROR");
                }

            }
            limparCampos();
            listar();
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyTyped
        // TODO add your handling code here:
        soNumeros(evt, false);
    }//GEN-LAST:event_jTextFieldNumeroKeyTyped

    private void jTextFieldValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorKeyTyped
        // TODO add your handling code here:
        soNumeros(evt, isDouble(jTextFieldValor));
    }//GEN-LAST:event_jTextFieldValorKeyTyped

    private void jTextFieldAtotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAtotalKeyTyped
        // TODO add your handling code here:
        soNumeros(evt, isDouble(jTextFieldAtotal));
    }//GEN-LAST:event_jTextFieldAtotalKeyTyped

    private void jTextFieldDimencaoFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDimencaoFKeyTyped
        // TODO add your handling code here:
        soNumeros(evt, isDouble(jTextFieldDimencaoF));
    }//GEN-LAST:event_jTextFieldDimencaoFKeyTyped

    private void jTextFieldDimencaoLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDimencaoLKeyTyped
        // TODO add your handling code here:
        soNumeros(evt, isDouble(jTextFieldDimencaoL));
    }//GEN-LAST:event_jTextFieldDimencaoLKeyTyped

    private void jTextFieldCodBuscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodBuscKeyTyped
        // TODO add your handling code here:
        switch(jComboBoxBusc.getSelectedItem().toString()){
            case "Codigo":
                soNumeros(evt, false);
                break;
            case "Valor":
                soNumeros(evt, isDouble(jTextFieldCodBusc));
                break;
        }
    }//GEN-LAST:event_jTextFieldCodBuscKeyTyped

    private void jButtonDetalheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalheActionPerformed
        // TODO add your handling code here:
        jTabbedPaneGuias.setSelectedIndex(1);// selecionar a aba.
        jTabbedPaneGuias.setEnabledAt(0, false);
        jTabbedPaneGuias.setEnabledAt(1, true);
        preencherCampos(getCod(jList1.getSelectedValue().toString()));
        desativarCampos();
    }//GEN-LAST:event_jButtonDetalheActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        if (jList1.isSelectionEmpty()) {
            jButtonDetalhe.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
        } else {
            jButtonDetalhe.setEnabled(true);
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int cod = getCod(jList1.getSelectedValue().toString());
        if (listaTerreno.excluir(cod)) {
            JOptionPane.showMessageDialog(this, "Excluido com sucesso.");
            if (listaTerreno.escreverArquivo()) {
                JOptionPane.showMessageDialog(null, "Alterações e exclusão Bem Sucedida!");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi alterado ERROR!");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir.");
        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenarActionPerformed
        int escolha = Integer.valueOf(JOptionPane.showInputDialog("Selecione Uma Opção:\n 1- Por Código\n 2- Por Valor\n 3- Por Área Total\n 4- Voltar"));
        switch (escolha) {
            case 1:
                listaTerreno.ordenarCodigo();
                DefaultListModel modelo = new DefaultListModel();
                List<Imovel> modelo1 = listaTerreno.getLista();
                for (Imovel imovel : modelo1) {
                    modelo.addElement(imovel.toString());
                }
                jList1.setModel(modelo);
                break;
            case 2:
                listaTerreno.ordenarValor();
                DefaultListModel modeloV = new DefaultListModel();
                List<Imovel> modelo2 = listaTerreno.getLista();
                for (Imovel imovel : modelo2) {
                    modeloV.addElement(imovel.toString());
                }
                jList1.setModel(modeloV);
                break;
            case 3:
                listaTerreno.ordenarArea();
                DefaultListModel modeloA = new DefaultListModel();
                List<Imovel> modelo3 = listaTerreno.getLista();
                for (Imovel imovel : modelo3) {
                    modeloA.addElement(imovel.toString());
                }
                jList1.setModel(modeloA);
                break;
            case 4:
                break;
            default:
                JOptionPane.showMessageDialog(null, "Favor , Digitar um Número Válido");

        }
    }//GEN-LAST:event_jButtonOrdenarActionPerformed

    private void jTextFieldCodBuscFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodBuscFocusLost
        // TODO add your handling code here:
        if(jTextFieldCodBusc.getText().trim().equals(".")){
            jTextFieldCodBusc.setText("");
        }
    }//GEN-LAST:event_jTextFieldCodBuscFocusLost

    private void jComboBoxBuscItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxBuscItemStateChanged
        // TODO add your handling code here:
        jTextFieldCodBusc.setText("");
    }//GEN-LAST:event_jComboBoxBuscItemStateChanged
//Preencher pra quando eu quiser ver detalhes.

    /**
     * Método para retirar o código do toString da classe sala comercial
     *
     * @param cod - String que veio do toString da classe
     * @return - retorna um inteiro com o código
     */
    private int getCod(String cod) {
        int end = 0;
        for (int i = 8; i < cod.length(); i++) {
            if (cod.charAt(i) == '-') {
                end = i - 1;
                break;
            }
        }

        cod = cod.substring(8, end);
        return Integer.parseInt(cod);
    }

    
    private void preencherCampos(int cod) {
        Terreno imovel = (Terreno) listaTerreno.consultar(cod);
        jTextFieldCidade.setText(imovel.getCidade());
        jTextFieldAtotal.setText(String.valueOf(imovel.getAreaTotal()));
        jTextFieldBairro.setText(imovel.getBairro());
        jTextFieldDescricao.setText(imovel.getDescricao());
        jTextFieldDimencaoF.setText(String.valueOf(imovel.getDimensaoFrente()));
        jTextFieldDimencaoL.setText(String.valueOf(imovel.getDimensaoLado()));
        jTextFieldLog.setText(imovel.getLogradouro());
        jTextFieldNumero.setText(String.valueOf(imovel.getNumero()));
        jTextFieldValor.setText(String.valueOf(imovel.getValor()));
    }

    public void limparCampos() {
        jTextFieldAtotal.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jTextFieldDescricao.setText("");
        jTextFieldDimencaoF.setText("");
        jTextFieldDimencaoL.setText("");
        jTextFieldNumero.setText("");
        jTextFieldValor.setText("");
        jTextFieldLog.setText("");
    }

    private void mudarAbas(int fim, int inicio) {
        jTabbedPaneGuias.setEnabledAt(fim, false);
        jTabbedPaneGuias.setEnabledAt(inicio, true);
        jTabbedPaneGuias.setSelectedIndex(inicio);
    }

    public void listar() {
        DefaultListModel modelo = new DefaultListModel();
        List<Imovel> modelo1 = listaTerreno.getLista();
        for (Imovel imovel : modelo1) {
            modelo.addElement(imovel.toString());
        }
        jList1.setModel(modelo);
    }

    public void busca(int codigo) {
        DefaultListModel modelo = new DefaultListModel();
        Imovel modelo1 = listaTerreno.consultar(codigo);
        if (modelo1 == null) {
            JOptionPane.showMessageDialog(null, "Imóvel não encontrado");
        } else {
            modelo.addElement(modelo1.toString());
        }
        jList1.setModel(modelo);

    }

    /**
     * Metodo para verificar um campo de texto, verifica se já possui um char ==
     * '.' para campos double
     *
     * @param campo - javax.swing.JTextField, ou seja, o campo que deseja fazer
     * a verificação
     * @return - true caso o campo ainda possa colocar o '.' e false caso
     * contrário
     */
    public boolean isDouble(javax.swing.JTextField campo) {
        boolean isDouble = true;
        String aux = campo.getText();
        for (int i = 0; i < aux.length(); i++) {
            if (aux.charAt(i) == '.') {
                isDouble = false;
                break;
            }
        }
        return isDouble;
    }

    public void desativarCampos() {
        jTextFieldAtotal.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldCidade.setEnabled(false);
        jTextFieldDescricao.setEnabled(false);
        jTextFieldDimencaoF.setEnabled(false);
        jTextFieldDimencaoL.setEnabled(false);
        jTextFieldLog.setEnabled(false);
        jTextFieldNumero.setEnabled(false);
        jTextFieldValor.setEnabled(false);
        jButtonSalvar.setVisible(false);
    }

    public void ativarCampos() {
        jTextFieldAtotal.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldDescricao.setEnabled(true);
        jTextFieldDimencaoF.setEnabled(true);
        jTextFieldDimencaoL.setEnabled(true);
        jTextFieldLog.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
        jTextFieldValor.setEnabled(true);
        jButtonSalvar.setVisible(true);
    }

    public void soNumeros(java.awt.event.KeyEvent evt, boolean isDouble) {
        char c = evt.getKeyChar();
        if (isDouble) {
            if (Character.isDigit(c) || c == '.') {

            } else {
                evt.consume();
            }
        } else if (Character.isDigit(c)) {

        } else {
            evt.consume();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTerreno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTerreno(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarC;
    private javax.swing.JButton jButtonDetalhe;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonOrdenar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltando;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox jComboBoxBusc;
    private javax.swing.JLabel jLabelAreaTotal;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelDimencaoL;
    private javax.swing.JLabel jLabelDimençaoF;
    private javax.swing.JLabel jLabelLog;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCadastrar;
    private javax.swing.JScrollPane jScrollPaneLista;
    private javax.swing.JTabbedPane jTabbedPaneGuias;
    private javax.swing.JTextField jTextFieldAtotal;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCodBusc;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldDimencaoF;
    private javax.swing.JTextField jTextFieldDimencaoL;
    private javax.swing.JTextField jTextFieldLog;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
public void listarCodigo(int cod) {
        DefaultListModel listModel = new DefaultListModel();
        List<Imovel> terrenoc;
        terrenoc = listaTerreno.getLista();//Atribui a lista da classe Lista a variável
        if (cod == -1) {
            //Percorre a lista e insere os resultados em listModel(Lista padrão)
            for (Imovel home : terrenoc) {
                listModel.addElement(home.toString());

            }
        } else {

            Imovel novo = listaTerreno.consultar(cod);
            if (novo != null) {
                listModel.addElement(novo.toString());
            }

        }

        jList1.setModel(listModel);
    }

    public void listarValor(double valor) {
        DefaultListModel listModel = new DefaultListModel();
        List<Imovel> terrenoValor = listaTerreno.pesquisaValor(valor);
        if (terrenoValor == null) {
            for (Imovel home : terrenoValor) {
                listModel.addElement(home);

            }
            jList1.setModel(listModel);
        } else {

            if (terrenoValor != null) {
                for (Imovel home : terrenoValor) {
                    listModel.addElement(home);

                }
                jList1.setModel(listModel);
            } else {

                jList1.setModel(listModel);

            }

        }

    }

    private void listarBairro(String bairro) {
        DefaultListModel listModel = new DefaultListModel();
        List<Imovel> terreno;
        List<Imovel> terrenoBairro = new ArrayList();
        terreno = listaTerreno.getLista();
        if (bairro.equals("")) {
            for (Imovel terrenoB : terreno) {
                listModel.addElement(terrenoB);

            }
            jList1.setModel(listModel);
        } else {
            terreno = listaTerreno.pesquisaBairro(bairro);
            if (terreno != null) {
                for (Imovel terrenoB : terreno) {
                    
                    listModel.addElement(terrenoB);
                }
                jList1.setModel(listModel);
            } else {
                jList1.setModel(listModel);
            }
        }
    }
}
