/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unipampa.rp2.frames;

import java.util.List;
import org.unipampa.rp2.listaimoveis.Lista;
import org.unipampa.rp2.tiposimoveis.Imovel;

/**
 *
 * @author unipampa
 */
public class FrameApartamento extends javax.swing.JFrame {

    /**
     * Creates new form FrameApartamento
    */
    private Lista ListaApartamento;
        private List<Imovel> Apartamento;
    
    public FrameApartamento(Lista ListaApartamento) {
        initComponents();
        
         this.setLocationRelativeTo(null);
        this.setTitle("Imobiliária - Apartamento");
        
        this.ListaApartamento = ListaApartamento;
       
        jTabbedPaneApartamento.setEnabledAt(0, true);
        
    }

    private FrameApartamento() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneApartamento = new javax.swing.JTabbedPane();
        jPanelApartamentoConsultar = new javax.swing.JPanel();
        jLabelcodApartamento = new javax.swing.JLabel();
        jTextFieldCodApartamento = new javax.swing.JTextField();
        jButtonConsultarApartamento = new javax.swing.JButton();
        jButtonConsultarVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListListaApartamento = new javax.swing.JList<>();
        jPanelApartamentoAdicionar = new javax.swing.JPanel();
        jLabelCodApartamento = new javax.swing.JLabel();
        jTextFieldAddCodApartamento = new javax.swing.JTextField();
        jLabelAddLogradouro = new javax.swing.JLabel();
        jTextFieldAddApartamentoLogradouro = new javax.swing.JTextField();
        jLabelAddApartamentoNum = new javax.swing.JLabel();
        jTextFieldAddApartamentoNum = new javax.swing.JTextField();
        jLabelAddApartamentoBairro = new javax.swing.JLabel();
        jTextFieldAddApartamentoBairro = new javax.swing.JTextField();
        jLabelAddApartamentoCidade = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanelApartamentoExcluir = new javax.swing.JPanel();
        jPanelApartamentoEditar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelcodApartamento.setText("Código do Apartamento:");

        jButtonConsultarApartamento.setText("Consultar");

        jButtonConsultarVoltar.setText("Voltar");
        jButtonConsultarVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarVoltarActionPerformed(evt);
            }
        });

        jListListaApartamento.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListListaApartamento);

        javax.swing.GroupLayout jPanelApartamentoConsultarLayout = new javax.swing.GroupLayout(jPanelApartamentoConsultar);
        jPanelApartamentoConsultar.setLayout(jPanelApartamentoConsultarLayout);
        jPanelApartamentoConsultarLayout.setHorizontalGroup(
            jPanelApartamentoConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApartamentoConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelApartamentoConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelApartamentoConsultarLayout.createSequentialGroup()
                        .addComponent(jLabelcodApartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jButtonConsultarApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelApartamentoConsultarLayout.createSequentialGroup()
                        .addComponent(jButtonConsultarVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanelApartamentoConsultarLayout.setVerticalGroup(
            jPanelApartamentoConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApartamentoConsultarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelApartamentoConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcodApartamento)
                    .addComponent(jTextFieldCodApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultarApartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButtonConsultarVoltar)
                .addContainerGap())
        );

        jTabbedPaneApartamento.addTab("Consultar", jPanelApartamentoConsultar);

        jLabelCodApartamento.setText("Código:");

        jLabelAddLogradouro.setText("* Logradouro:");

        jLabelAddApartamentoNum.setText("* Número:");

        jLabelAddApartamentoBairro.setText("* Bairro:");

        jLabelAddApartamentoCidade.setText("* Cidade:");

        javax.swing.GroupLayout jPanelApartamentoAdicionarLayout = new javax.swing.GroupLayout(jPanelApartamentoAdicionar);
        jPanelApartamentoAdicionar.setLayout(jPanelApartamentoAdicionarLayout);
        jPanelApartamentoAdicionarLayout.setHorizontalGroup(
            jPanelApartamentoAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApartamentoAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelApartamentoAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelAddApartamentoCidade)
                    .addComponent(jLabelAddApartamentoNum)
                    .addComponent(jLabelAddLogradouro)
                    .addComponent(jLabelCodApartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelApartamentoAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAddApartamentoLogradouro)
                    .addGroup(jPanelApartamentoAdicionarLayout.createSequentialGroup()
                        .addComponent(jTextFieldAddCodApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelApartamentoAdicionarLayout.createSequentialGroup()
                        .addGroup(jPanelApartamentoAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelApartamentoAdicionarLayout.createSequentialGroup()
                                .addComponent(jTextFieldAddApartamentoNum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAddApartamentoBairro)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAddApartamentoBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelApartamentoAdicionarLayout.setVerticalGroup(
            jPanelApartamentoAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApartamentoAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelApartamentoAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodApartamento)
                    .addComponent(jTextFieldAddCodApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelApartamentoAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddLogradouro)
                    .addComponent(jTextFieldAddApartamentoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelApartamentoAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddApartamentoNum)
                    .addComponent(jTextFieldAddApartamentoNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddApartamentoBairro)
                    .addComponent(jTextFieldAddApartamentoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelApartamentoAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddApartamentoCidade)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jTabbedPaneApartamento.addTab("Adicionar", jPanelApartamentoAdicionar);

        javax.swing.GroupLayout jPanelApartamentoExcluirLayout = new javax.swing.GroupLayout(jPanelApartamentoExcluir);
        jPanelApartamentoExcluir.setLayout(jPanelApartamentoExcluirLayout);
        jPanelApartamentoExcluirLayout.setHorizontalGroup(
            jPanelApartamentoExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        jPanelApartamentoExcluirLayout.setVerticalGroup(
            jPanelApartamentoExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        jTabbedPaneApartamento.addTab("Excluir", jPanelApartamentoExcluir);

        javax.swing.GroupLayout jPanelApartamentoEditarLayout = new javax.swing.GroupLayout(jPanelApartamentoEditar);
        jPanelApartamentoEditar.setLayout(jPanelApartamentoEditarLayout);
        jPanelApartamentoEditarLayout.setHorizontalGroup(
            jPanelApartamentoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        jPanelApartamentoEditarLayout.setVerticalGroup(
            jPanelApartamentoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        jTabbedPaneApartamento.addTab("Editar", jPanelApartamentoEditar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneApartamento)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneApartamento)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarVoltarActionPerformed
        Inicial voltar = new Inicial();
        voltar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonConsultarVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarApartamento;
    private javax.swing.JButton jButtonConsultarVoltar;
    private javax.swing.JLabel jLabelAddApartamentoBairro;
    private javax.swing.JLabel jLabelAddApartamentoCidade;
    private javax.swing.JLabel jLabelAddApartamentoNum;
    private javax.swing.JLabel jLabelAddLogradouro;
    private javax.swing.JLabel jLabelCodApartamento;
    private javax.swing.JLabel jLabelcodApartamento;
    private javax.swing.JList<String> jListListaApartamento;
    private javax.swing.JPanel jPanelApartamentoAdicionar;
    private javax.swing.JPanel jPanelApartamentoConsultar;
    private javax.swing.JPanel jPanelApartamentoEditar;
    private javax.swing.JPanel jPanelApartamentoExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneApartamento;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldAddApartamentoBairro;
    private javax.swing.JTextField jTextFieldAddApartamentoLogradouro;
    private javax.swing.JTextField jTextFieldAddApartamentoNum;
    private javax.swing.JTextField jTextFieldAddCodApartamento;
    private javax.swing.JTextField jTextFieldCodApartamento;
    // End of variables declaration//GEN-END:variables
}
